<!doctype html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	
		<title>Titanium Developer Launch failed at builder.py » Community Questions &amp; Answers </title>
	
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="../../related/favicon.png" rel="shortcut icon" type="image/png">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700" rel="stylesheet" type="text/css">
	<link href="//d3ilu1xuwhtfe2.cloudfront.net/e8e0ebd/css/style.css" rel="stylesheet" type="text/css">
	<link href="../../related/qa.css" rel="stylesheet" type="text/css">
	<link href="../../related/hybrid.css" rel="stylesheet" type="text/css">
	
	<link href="../../related/overrides.css" rel="stylesheet" type="text/css">
</head>
<body>

<div class='mast'>    <div class='container'>        <div class='row'>            <div class='col-sm-12'>                <div class='masthead'><h1>Titanium Community Questions & Answer Archive</h1><h2>We felt that 6+ years of knowledge should not die so this is the Titanium Community Questions &amp; Answer Archive</h2></div>            </div>        </div>    </div></div>

<main class="container">
	<div class="row">
		<div class="col-sm-12">
			
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<article class="question-container">
	<div class="question">
		<header>
			<h1>Titanium Developer Launch failed at builder.py</h1>
		</header>
		<section>
			<p>I am getting the below error for titanium mobile 1.5.1 and 1.6.0 on Ubuntu 10.04 64-bit. I installed ia32-libs also. I also got the same below error on Windows 7 also.  There is no fix mentioned online. I have been struggling for last one week and gave up the hope. I have also build using scons with JAVA_HOME and android-sdk paths, but no use. </p>
<p>[INFO] Compiling Javascript Resources …<br>[INFO] Compiling Android Resources… This could take some time<br>[ERROR] Error in compiler. &lt;type &#39;exceptions.OSError&#39;&gt;, [Errno 2] No such file or directory; Traceback (most recent call last):     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1587, in &lt;module&gt;     s.build_and_run(False,avd_id)     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1480, in build_and_run     launched, launch_failed = self.package_and_deploy()     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1112, in package_and_deploy     output = run.run([self.jarsigner, &#39;-storepass&#39;, self.keystore_pass, &#39;-keystore&#39;, self.keystore, &#39;-signedjar&#39;, app_apk, unsigned_apk, self.keystore_alias])     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;run.py&quot;, line 36, in run     (so,se) = subprocess.Popen(args, stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()     File &quot;&#x2F;usr&#x2F;lib&#x2F;python2.6&#x2F;subprocess.py&quot;, line 633, in <strong>init</strong>     errread, errwrite) File &quot;&#x2F;usr&#x2F;lib&#x2F;python2.6&#x2F;subprocess.py&quot;, line 1139, in _execute_child     raise child_exception    OSError: [Errno 2] No such file or directory</p>

		</section>
		<footer>
			<div class="author">
				&mdash; asked <span title="December 28th 2010, 11:39:34 pm">December 28th 2010</span>
				by <span class='authorname'>Niharika Bitra</span>
			</div>

			

			<section>
				<h5>2 Comments</h5>
				
					<ul class="comments">
					
						<li class="comment">
							<div><p>I&#39;m having the same issue as you, did you find a solution? if you did could you please post your solution.</p>
</div>
							<div class="author">
								&mdash; commented <span title="January 14th 2011, 1:43:53 pm">January 14th 2011</span>
								by <span class='authorname'>Arturo Castro</span>
							</div>
						</li>
					
						<li class="comment">
							<div><p>Arturo - if you open your own question, someone will help you directly. Read the <a href="http:&#x2F;&#x2F;developer.appcelerator.com&#x2F;guides&#x2F;en&#x2F;contribute.html#participating_in_the_q&amp;a">Participating in the Q&amp;A</a> guide first, so that you know the best way to use the Q&amp;A.</p>
</div>
							<div class="author">
								&mdash; commented <span title="January 14th 2011, 3:43:35 pm">January 14th 2011</span>
								by <span class='authorname'>Paul Dowsett</span>
							</div>
						</li>
					
					</ul>
				
			</section>
		</footer>
		<aside class="vote-box">
			<div class="score"><span>-1</span> Votes</div>
			<div class="answers"><span>3</span> Answers</div>
		</aside>
	</div>

	<hr>

	<h3>3 Answers</h3>

	
		<ul class="answers">
			
				<li class="answer">
				
					<article id="answer-170521">
				
						<section>
							<p>Creating symbolic link for jarsigner in &#x2F;usr&#x2F;bin fixed the issue. So, java, javac and jarsigner should be in &#x2F;usr&#x2F;bin. If they don&#39;t exist there, create the symbolic links in &#x2F;usr&#x2F;bin because they exist in $JAVA_HOME&#x2F;bin.</p>

						</section>
						<footer>
							<div class="author">
								&mdash; answered <span title="December 30th 2010, 1:37:18 am">December 30th 2010</span>
								by <span class='authorname'>Niharika Bitra</span><br>
								<a class="icon-bg icon-link" href="question/94711/titanium-developer-launch-failed-at-builderpy.html#answer-170521" rel="permalink">permalink</a>
							</div>

							<h5>1 Comment</h5>
							
								<ul class="comments">
								
									<li class="comment">
										<p><p>Niharika</p>
<p>It&#39;s great that you found a solution, but if you could use the Q&amp;A as per the guidelines in <a href="http:&#x2F;&#x2F;developer.appcelerator.com&#x2F;guides&#x2F;en&#x2F;contribute.html#participating_in_the_q&amp;a">Participating in the Q&amp;A</a> it would work better for everyone.</p>
</p>
										<div class="author">
											&mdash; commented <span title="December 30th 2010, 9:33:12 am">December 30th 2010</span>
											by <span class='authorname'>Paul Dowsett</span>
										</div>
									</li>
								
								</ul>
							
						</footer>
						<aside class="vote-box">
							<div class="score"><span>0</span> Votes</div>
						</aside>
					</article>
				</li>
			
				<li class="answer">
				
					<article id="answer-170411">
				
						<section>
							<p>It&#39;s very important that you ensure that your android environment is set up correctly. Have you followed the advice in <a href="http:&#x2F;&#x2F;developer.appcelerator.com&#x2F;guides&#x2F;en&#x2F;getting_started.html#preparing_for_android_development">Preparing for Android development</a>, in particular the Java section?</p>
<p>I use Ubuntu on a 64bit platform all the time, and find that most problems are caused by incorrect permissions. Follow the instructions in <a href="http:&#x2F;&#x2F;developer.appcelerator.com&#x2F;guides&#x2F;en&#x2F;troubleshooting_your_installation.html">Troubleshooting Your Installation</a> to resolve these kinds of issues.</p>
<p>Hope this helps</p>

						</section>
						<footer>
							<div class="author">
								&mdash; answered <span title="December 29th 2010, 9:12:20 pm">December 29th 2010</span>
								by <span class='authorname'>Paul Dowsett</span><br>
								<a class="icon-bg icon-link" href="question/94711/titanium-developer-launch-failed-at-builderpy.html#answer-170411" rel="permalink">permalink</a>
							</div>

							<h5>2 Comments</h5>
							
								<ul class="comments">
								
									<li class="comment">
										<p><p>I selected Filter as Trace. But it didn&#39;t help much. I am getting the emulator, but throwing the same error. I verified the permissions also. Here is the Trace for your advice.<br>[DEBUG] from JAR &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;modules&#x2F;titanium-ui.jar =&gt; ti&#x2F;modules&#x2F;titanium&#x2F;ui&#x2F;widget&#x2F;webview&#x2F;binding.js<br>[DEBUG] from JAR &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;modules&#x2F;titanium-ui.jar =&gt; ti&#x2F;modules&#x2F;titanium&#x2F;ui&#x2F;widget&#x2F;webview&#x2F;binding.min.js<br>[DEBUG] from JAR &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;modules&#x2F;titanium-ui.jar =&gt; ti&#x2F;modules&#x2F;titanium&#x2F;ui&#x2F;widget&#x2F;webview&#x2F;json2.js<br>[DEBUG] from JAR &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;modules&#x2F;titanium-media.jar =&gt; org&#x2F;appcelerator&#x2F;titanium&#x2F;bindings&#x2F;media.json<br>[DEBUG] jarsigner -storepass tirocks -keystore &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;dev_keystore -signedjar &#x2F;home&#x2F;nbitra&#x2F;appcelerator&#x2F;TestApp&#x2F;build&#x2F;android&#x2F;bin&#x2F;app.apk &#x2F;home&#x2F;nbitra&#x2F;appcelerator&#x2F;TestApp&#x2F;build&#x2F;android&#x2F;bin&#x2F;app-unsigned.apk tidev<br>[ERROR] Error in compiler. &lt;type &#39;exceptions.OSError&#39;&gt;, [Errno 2] No such file or directory; Traceback (most recent call last):     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1587, in &lt;module&gt;     s.build_and_run(False,avd_id)     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1480, in build_and_run     launched, launch_failed = self.package_and_deploy()     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;builder.py&quot;, line 1112, in package_and_deploy     output = run.run([self.jarsigner, &#39;-storepass&#39;, self.keystore_pass, &#39;-keystore&#39;, self.keystore, &#39;-signedjar&#39;, app_apk, unsigned_apk, self.keystore_alias])     File &quot;&#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;run.py&quot;, line 36, in run     (so,se) = subprocess.Popen(args, stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()     File &quot;&#x2F;usr&#x2F;lib&#x2F;python2.6&#x2F;subprocess.py&quot;, line 633, in <strong>init</strong>     errread, errwrite) File &quot;&#x2F;usr&#x2F;lib&#x2F;python2.6&#x2F;subprocess.py&quot;, line 1139, in _execute_child     raise child_exception    OSError: [Errno 2] No such file or directory<br>[TRACE] D&#x2F;dalvikvm( 321): DexOpt: load 323ms, verify 687ms, opt 18ms<br>[TRACE] D&#x2F;installd( 35): DexInv: — END &#39;&#x2F;system&#x2F;app&#x2F;Music.apk&#39; (success) —<br>[TRACE] D&#x2F;OtaStartupReceiver( 185): Not a CDMA phone, no need to process OTA<br>[TRACE] I&#x2F;ActivityManager( 111): Start proc com.android.mms for broadcast com.android.mms&#x2F;.transaction.MmsSystemEventReceiver: pid=323 uid=10015 gids={3003, 1015}<br>[TRACE] I&#x2F;RecoverySystem( 111): No recovery log file<br>[TRACE] D&#x2F;dalvikvm( 262): GC_FOR_MALLOC freed 4149 objects &#x2F; 487536 bytes in 257ms<br>[TRACE] D&#x2F;installd( 35): DexInv: — BEGIN &#39;&#x2F;system&#x2F;app&#x2F;Mms.apk&#39; —<br>[TRACE] V&#x2F;CheckinRequestBuilder( 262): pre-froyo android id is 0<br>[TRACE] I&#x2F;CheckinTask( 262): Sending checkin request (414 bytes)<br>[TRACE] D&#x2F;dalvikvm( 329): DexOpt: load 476ms, verify 1117ms, opt 50ms</p>
</p>
										<div class="author">
											&mdash; commented <span title="December 30th 2010, 12:35:24 am">December 30th 2010</span>
											by <span class='authorname'>Niharika Bitra</span>
										</div>
									</li>
								
									<li class="comment">
										<p><p>It is giving error right after<br>[DEBUG] jarsigner -storepass tirocks -keystore &#x2F;home&#x2F;nbitra&#x2F;.titanium&#x2F;mobilesdk&#x2F;linux&#x2F;1.6.0&#x2F;android&#x2F;dev_keystore -signedjar &#x2F;home&#x2F;nbitra&#x2F;appcelerator&#x2F;TestApp&#x2F;build&#x2F;android&#x2F;bin&#x2F;app.apk &#x2F;home&#x2F;nbitra&#x2F;appcelerator&#x2F;TestApp&#x2F;build&#x2F;android&#x2F;bin&#x2F;app-unsigned.apk tidev</p>
</p>
										<div class="author">
											&mdash; commented <span title="December 30th 2010, 12:37:55 am">December 30th 2010</span>
											by <span class='authorname'>Niharika Bitra</span>
										</div>
									</li>
								
								</ul>
							
						</footer>
						<aside class="vote-box">
							<div class="score"><span>-1</span> Votes</div>
						</aside>
					</article>
				</li>
			
				<li class="answer">
				
					<article id="answer-170661">
				
						<section>
							<p>The easiest way to configure the default Java version used on an Ubuntu system is by using the following command at the Ubuntu command line:</p>
<pre><code class="hljs">sudo <span class="hljs-operator"><span class="hljs-keyword">update</span>-alternatives <span class="hljs-comment">--config java</span>
sudo <span class="hljs-keyword">update</span>-alternatives <span class="hljs-comment">--config javac</span></span>
</code></pre>
						</section>
						<footer>
							<div class="author">
								&mdash; answered <span title="December 30th 2010, 9:46:23 am">December 30th 2010</span>
								by <span class='authorname'>Paul Dowsett</span><br>
								<a class="icon-bg icon-link" href="question/94711/titanium-developer-launch-failed-at-builderpy.html#answer-170661" rel="permalink">permalink</a>
							</div>

							<h5>0 Comments</h5>
							
						</footer>
						<aside class="vote-box">
							<div class="score"><span>-1</span> Votes</div>
						</aside>
					</article>
				</li>
			
		</ul>
	
</article>

		</div>
		<div class="col-sm-3"></div>
	</div>
	<div class="row"><div class="signoff">The ownership of individual contributions to this community generated content is retained by the authors of their contributions.<br>All trademarks remain the property of the respective owner.</div></div>
</main>


</body>
</html>
